title: Born in New York
description: Diary of little Hana growing up
url: "https://borninnewyork.net" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog

sass:
    sass_dir: _sass
# Comments
# discus_identifier: born-in-new-york
